### ISSUE TITLE
Installazione con TAR al CRS4

### ISSUE THREAD

**Issue by lmssdd** [tdm-project/tdm-edge#2]
Simone ed io abbiamo provato a seguire le istruzioni per l'installazione qui riportate https://github.com/tdm-project/tdm-edge/wiki/TDM-Edge-Gateway-Installation

La raspberry è una 3B+
Ci troviamo nella sede di Pula

Abbiamo verificato che: 
- Non parte l’access point
- systemctl disable start_ap dice che non esiste il servizio
- il comando sudo non è presente
- siamo dovuti entrare come root (pwd root)
- il comando git non è presente nella distribuzione
- non siamo riusciti a configurare la rete WiFi seguendo la procedura descritta
- la distribuzione raspbian stretch sulla stessa macchina funziona senza alcun problema sia come AP che per il collegamento WiFi

**Comment by mgaggero** [comment]
Quale link al tar avete usato?
Provate questa procedura: https://github.com/tdm-project/tdm-edge/wiki/TDM-Edge-Gateway-Installation-with-Etcher

**Comment by lmssdd** [comment]
La procedura con Etcher funziona.
Nella documentazione manca la parte relativa al ridimensionamento delle partizioni.
Di seguito una proposta di integrazione alla documentazione:

Log in the edge device 
ssh alarm@XXX.XXX.XXX.XXX

Modify the partition table.

`sudo fdisk /dev/mmcblk0`

print the partition table

`p`

delete the second partition

`d`
`2`

Create the second partition again

`n`

then accept all the default parameters hitting enter. Remove the ext4 signature if asked.

Write the new partition table

`w`

Reboot the system

`reboot`

Login again as alarm

`ssh alarm@XXX.XXX.XXX.XXX`

check the available space

`df -h`

resize the second partition

`sudo resize2fs /dev/mmcblk0p2`

wait and don’t panic.

Check the disk space again.

`df -h`

All the SD card is now available, yayyy!

**Comment by mgaggero** [comment]
Grazie! Ho integrato la documentazione aggiungendo una pagina ad hoc.

**Comment by lmssdd** [comment]
(y)
